/*
 * SPDX-FileCopyrightText: Copyright (c) 2019-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <raft/core/detail/macros.hpp>
#include <raft/util/cuda_utils.cuh>
#include <raft/util/cudart_utils.hpp>
#include <raft/util/kernel_launch.hpp>
#include <raft/util/vectorized.cuh>

#include <cooperative_groups.h>
#include <cuda/iterator>
#include <cuda/std/random>

namespace raft {
namespace random {
namespace detail {

// SplitMix64 reference: https://prng.di.unimi.it/splitmix64.c
struct splitmix64 {
  using result_type = uint64_t;

  RAFT_INLINE_FUNCTION explicit splitmix64(result_type seed) : state_{seed} {}

  [[nodiscard]] RAFT_INLINE_FUNCTION static constexpr result_type min() noexcept { return 0; }

  [[nodiscard]] RAFT_INLINE_FUNCTION static constexpr result_type max() noexcept
  {
    return ~result_type{0};
  }

  RAFT_INLINE_FUNCTION result_type operator()() noexcept
  {
    auto z = (state_ += 0x9e3779b97f4a7c15ULL);
    z      = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z      = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
  }

 private:
  result_type state_;
};

/**
 * @brief Generate permutation indices without copying input data.
 *
 * @tparam IntType Output permutation index type
 * @tparam IdxType Input index and extent type
 * @tparam TPB Threads per block
 * @tparam ITEMS_PER_THREAD Permutation indices generated by each thread
 * @tparam ShuffleIterator Iterator that maps output indices to input indices
 *
 * @param[out] perms Generated permutation indices
 * @param[in] shuffled_indices Iterator that defines the permutation
 * @param[in] N Number of indices to generate
 */
template <typename IntType,
          typename IdxType,
          int TPB,
          int ITEMS_PER_THREAD,
          typename ShuffleIterator>
RAFT_KERNEL permsOnlyKernel(IntType* perms, ShuffleIterator shuffled_indices, IdxType N)
{
  IdxType base = IdxType(blockIdx.x) * IdxType(TPB * ITEMS_PER_THREAD) + threadIdx.x;
#pragma unroll
  for (int i = 0; i < ITEMS_PER_THREAD; i++) {
    IdxType idx = base + IdxType(i * TPB);
    if (idx < N) { perms[idx] = IntType(shuffled_indices[idx]); }
  }
}

/**
 * @brief Generate permutation indices and optionally copy permuted matrix rows.
 *
 * @tparam Type Input and output element type
 * @tparam IntType Output permutation index type
 * @tparam IdxType Input index and extent type
 * @tparam TPB Threads per block
 * @tparam rowMajor Whether the matrices use row-major layout
 * @tparam ShuffleIterator Iterator that maps output indices to input indices
 *
 * @param[out] perms Generated permutation indices, or nullptr
 * @param[out] out Permuted output matrix, or nullptr
 * @param[in] in Input matrix, or nullptr
 * @param[in] shuffled_indices Iterator that defines the permutation
 * @param[in] N Number of matrix rows
 * @param[in] D Number of matrix columns
 */
template <typename Type,
          typename IntType,
          typename IdxType,
          int TPB,
          bool rowMajor,
          typename ShuffleIterator>
RAFT_KERNEL permuteKernel(
  IntType* perms, Type* out, const Type* in, ShuffleIterator shuffled_indices, IdxType N, IdxType D)
{
  namespace cg        = cooperative_groups;
  const int WARP_SIZE = 32;

  int tid = threadIdx.x + blockIdx.x * blockDim.x;

  IntType outIdx = tid;
  IntType inIdx  = (tid < N) ? IntType(shuffled_indices[tid]) : IntType(0);

  if (perms != nullptr && tid < N) { perms[outIdx] = inIdx; }

  if (out == nullptr || in == nullptr) { return; }

  if (rowMajor) {
    cg::thread_block_tile<WARP_SIZE> warp = cg::tiled_partition<WARP_SIZE>(cg::this_thread_block());

    // The warp cooperatively copies its 32 rows one at a time so that the 32
    // lanes stride together along D, giving coalesced global loads and stores.
    // Copying row i needs lane i's (inIdx, outIdx);
    int laneID = threadIdx.x % WARP_SIZE;
    for (int i = 0; i < WARP_SIZE; ++i) {
      IntType inIdxI  = warp.shfl(inIdx, i);
      IntType outIdxI = warp.shfl(outIdx, i);
      if (outIdxI < N) {
#pragma unroll
        for (int j = laneID; j < D; j += WARP_SIZE) {
          out[outIdxI * D + j] = in[inIdxI * D + j];
        }
      }
    }
  } else {
#pragma unroll
    for (int j = 0; j < D; ++j) {
      if (tid < N) { out[outIdx + j * N] = in[inIdx + j * N]; }
    }
  }
}

// This is wrapped in a type to allow for partial template specialization
template <typename Type, typename IntType, typename IdxType, int TPB, bool rowMajor, int VLen>
struct permute_impl_t {
  /**
   * @brief Launch the permutation kernel with the widest valid vector type.
   *
   * @param[out] perms Generated permutation indices, or nullptr
   * @param[out] out Permuted output matrix
   * @param[in] in Input matrix
   * @param[in] N Number of matrix rows
   * @param[in] D Number of matrix columns
   * @param[in] nblks Number of thread blocks to launch
   * @param[in] shuffled_indices Iterator that defines the permutation
   * @param[in] stream CUDA stream on which to launch the kernel
   */
  template <typename ShuffleIterator>
  static void permuteImpl(IntType* perms,
                          Type* out,
                          const Type* in,
                          IdxType N,
                          IdxType D,
                          int nblks,
                          ShuffleIterator shuffled_indices,
                          cudaStream_t stream)
  {
    // determine vector type and set new pointers
    typedef typename raft::IOType<Type, VLen>::Type VType;
    VType* vout      = reinterpret_cast<VType*>(out);
    const VType* vin = reinterpret_cast<const VType*>(in);

    // check if we can execute at this vector length
    if (D % VLen == 0 && raft::is_aligned(vout, sizeof(VType)) &&
        raft::is_aligned(vin, sizeof(VType))) {
      raft::launch_kernel(stream,
                          nblks,
                          TPB,
                          permuteKernel<VType, IntType, IdxType, TPB, rowMajor>,
                          perms,
                          vout,
                          vin,
                          shuffled_indices,
                          N,
                          D / VLen);
    } else {  // otherwise try the next lower vector length
      permute_impl_t<Type, IntType, IdxType, TPB, rowMajor, VLen / 2>::permuteImpl(
        perms, out, in, N, D, nblks, shuffled_indices, stream);
    }
  }
};

// at vector length 1 we just execute a scalar version to break the recursion
template <typename Type, typename IntType, typename IdxType, int TPB, bool rowMajor>
struct permute_impl_t<Type, IntType, IdxType, TPB, rowMajor, 1> {
  /**
   * @brief Launch the scalar permutation kernel.
   *
   * @param[out] perms Generated permutation indices, or nullptr
   * @param[out] out Permuted output matrix
   * @param[in] in Input matrix
   * @param[in] N Number of matrix rows
   * @param[in] D Number of matrix columns
   * @param[in] nblks Number of thread blocks to launch
   * @param[in] shuffled_indices Iterator that defines the permutation
   * @param[in] stream CUDA stream on which to launch the kernel
   */
  template <typename ShuffleIterator>
  static void permuteImpl(IntType* perms,
                          Type* out,
                          const Type* in,
                          IdxType N,
                          IdxType D,
                          int nblks,
                          ShuffleIterator shuffled_indices,
                          cudaStream_t stream)
  {
    raft::launch_kernel(stream,
                        nblks,
                        TPB,
                        permuteKernel<Type, IntType, IdxType, TPB, rowMajor>,
                        perms,
                        out,
                        in,
                        shuffled_indices,
                        N,
                        D);
  }
};

/**
 * @brief Generate a keyed permutation and optionally apply it to a matrix.
 *
 * @tparam Type Input and output element type
 * @tparam IntType Output permutation index type
 * @tparam IdxType Input index and extent type
 * @tparam TPB Threads per block
 *
 * @param[out] perms Generated permutation indices, or nullptr
 * @param[out] out Permuted output matrix, or nullptr
 * @param[in] in Input matrix, or nullptr
 * @param[in] D Number of matrix columns
 * @param[in] N Number of matrix rows
 * @param[in] rowMajor Whether the matrices use row-major layout
 * @param[in] stream CUDA stream on which to launch kernels
 * @param[in] key Key used to construct the random bijection
 */
template <typename Type, typename IntType = int, typename IdxType = int, int TPB = 256>
void permute(IntType* perms,
             Type* out,
             const Type* in,
             IntType D,
             IntType N,
             bool rowMajor,
             cudaStream_t stream,
             uint64_t key)
{
  if (N <= 0 || (perms == nullptr && out == nullptr)) { return; }
  splitmix64 rng(key);
  cuda::shuffle_iterator shuffled_indices{cuda::random_bijection{N, rng}};

  if (out == nullptr) {
    constexpr int ITEMS_PER_THREAD = 8;
    auto nblks                     = raft::ceildiv(N, IntType(TPB * ITEMS_PER_THREAD));
    permsOnlyKernel<IntType, IntType, TPB, ITEMS_PER_THREAD>
      <<<nblks, TPB, 0, stream>>>(perms, shuffled_indices, N);
    RAFT_CUDA_TRY(cudaPeekAtLastError());
    return;
  }

  auto nblks = raft::ceildiv(N, (IntType)TPB);

  if (rowMajor) {
    permute_impl_t<Type,
                   IntType,
                   IdxType,
                   TPB,
                   true,
                   (16 / sizeof(Type) > 0) ? 16 / sizeof(Type) : 1>::permuteImpl(perms,
                                                                                 out,
                                                                                 in,
                                                                                 N,
                                                                                 D,
                                                                                 nblks,
                                                                                 shuffled_indices,
                                                                                 stream);
  } else {
    permute_impl_t<Type, IntType, IdxType, TPB, false, 1>::permuteImpl(
      perms, out, in, N, D, nblks, shuffled_indices, stream);
  }
}

};  // end namespace detail
};  // namespace random
}  // namespace raft
